# Numpy

Numeric Python


In [1]:
!pip install numpy

# Creating a Vector

In [2]:
import numpy as np

In [3]:
np.array?

In [4]:
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [5]:
print(v)

[1 2 3 4]


In [6]:
c = np.array([[1],[2],[3]])
c

array([[1],
       [2],
       [3]])

# Creating a Matrix

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
0th dimension --->   .
1st dimension --->   .______.

2nd dimension --->   .___|___.

3rd dimension --->   .___|___.
                        /
    
4th dimension
|
|
|
nth dimensions